/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 BaseFlag.glb --transform 
Files: BaseFlag.glb [5.08KB] > F:\Projects\exogenesis\frontend\public\models\structures\BaseFlag-transformed.glb [2.2KB] (57%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BaseFlag-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.mat22} />
      <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.mat10} />
    </group>
  )
}

useGLTF.preload('/BaseFlag-transformed.glb')
