/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Base Large.glb --transform 
Files: .\Base Large.glb [124.87KB] > C:\Projekte\exogenesis\frontend\public\models\structures\Base Large-transformed.glb [14.81KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Base Large-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base_Large.geometry} material={materials.Atlas} scale={100} />
    </group>
  )
}

useGLTF.preload('/Base Large-transformed.glb')
