/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Drill.glb --transform 
Files: Drill.glb [97.78KB] > F:\Projects\exogenesis\frontend\public\models\structures\Drill-transformed.glb [20.34KB] (79%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Drill-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.drill_structure.geometry} material={materials.spacebits_texture} scale={100} />
    </group>
  )
}

useGLTF.preload('/Drill-transformed.glb')
