/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Factory.glb --transform 
Files: Factory.glb [21.56KB] > F:\Projects\exogenesis\frontend\public\models\structures\Factory-transformed.glb [5.16KB] (76%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Factory-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Factory.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/Factory-transformed.glb')
