/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 golf hole flag.glb --transform 
Files: golf hole flag.glb [6.13KB] > F:\Projects\exogenesis\frontend\public\models\structures\golf hole flag-transformed.glb [3.03KB] (51%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/golf hole flag-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat22} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat10} />
    </group>
  )
}

useGLTF.preload('/golf hole flag-transformed.glb')
