/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Metropolis.glb --transform 
Files: Metropolis.glb [4.29MB] > F:\Projects\exogenesis\frontend\public\models\structures\Metropolis-transformed.glb [250.16KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Metropolis-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1172654828.geometry} material={materials.PaletteMaterial005} position={[0, 113.235, 15.96]} />
      <mesh geometry={nodes.Spaceship_BarbaraTheBee.geometry} material={materials.Atlas} />
      <mesh geometry={nodes.landingpad_small.geometry} material={materials['spacebits_texture.001']} position={[9.242, 4.749, 0]} scale={625.027} />
      <mesh geometry={nodes['Highrise_12-Mesh002'].geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes['Highrise_12-Mesh002_1'].geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes['Highrise_12-Mesh002_2'].geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes['Highrise_12-Mesh003'].geometry} material={materials.PaletteMaterial004} />
      <mesh geometry={nodes['Highrise_12-Mesh003_1'].geometry} material={materials.Texture_Signs} />
    </group>
  )
}

useGLTF.preload('/Metropolis-transformed.glb')
