/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pump_jack.glb --transform 
Files: pump_jack.glb [3.84MB] > F:\Projects\exogenesis\frontend\public\models\structures\pump_jack-transformed.glb [344.78KB] (91%)
Author: Renafox (https://sketchfab.com/kryik1023)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/pump-jack-021faf828156426bb99a1cf87b5cefad
Title: Pump Jack
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pump_jack-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Object001_Material_#73_0'].geometry} material={materials.Material_73} position={[0, 1.757, -0.754]} rotation={[0, -Math.PI / 2, 0]} scale={0.013} />
    </group>
  )
}

useGLTF.preload('/pump_jack-transformed.glb')
