/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Space Base Modules.glb --transform 
Files: Space Base Modules.glb [290.55KB] > F:\Projects\exogenesis\frontend\public\models\structures\Space Base Modules-transformed.glb [36.42KB] (87%)
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Space Base Modules-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.basemodule_A.geometry} material={materials.spacebits_texture} position={[3, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Space Base Modules-transformed.glb')
