/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Urban Park v1.glb --transform 
Files: Urban Park v1.glb [2.75MB] > C:\Projekte\exogenesis\frontend\public\models\structures\Urban Park v1-transformed.glb [117.82KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Urban Park v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1872301862.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/Urban Park v1-transformed.glb')
