/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Spaceship.glb --transform 
Files: Spaceship.glb [20.6KB] > F:\Projects\exogenesis\frontend\public\models\fleet\Spaceship-transformed.glb [4.7KB] (77%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Spaceship-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lo_poly_Spaceship_05_by_Liz_Reddington_1.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.Lo_poly_Spaceship_05_by_Liz_Reddington_1_1.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.Lo_poly_Spaceship_05_by_Liz_Reddington_1_2.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/Spaceship-transformed.glb')
