/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Earth.glb --transform 
Files: Earth.glb [70.85KB] > C:\Projekte\exogenesis\frontend\public\models\earth\Earth-transformed.glb [8.64KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Earth-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere002_1.geometry} material={materials['02___Default']} />
      <mesh geometry={nodes.Sphere002_1_1.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Sphere002_1_2.geometry} material={materials['03___Default']} />
    </group>
  )
}

useGLTF.preload('/Earth-transformed.glb')
