/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Jupiter.glb --transform 
Files: Jupiter.glb [69.13KB] > C:\Projekte\exogenesis\frontend\public\models\earth\Jupiter-transformed.glb [6.55KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Jupiter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Jupiter_Sphere.geometry} material={materials['Material.005']} />
    </group>
  )
}

useGLTF.preload('/Jupiter-transformed.glb')
