/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PlanetBv2.glb --transform 
Files: PlanetBv2.glb [58.56KB] > F:\Projects\exogenesis\frontend\public\models\earth\PlanetBv2-transformed.glb [10.01KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/PlanetBv2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Planet_6.geometry} material={materials.Atlas} />
    </group>
  )
}

useGLTF.preload('/PlanetBv2-transformed.glb')
