/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PlanetB.glb --transform 
Files: PlanetB.glb [58.76KB] > F:\Projects\exogenesis\frontend\public\models\earth\PlanetB-transformed.glb [9.32KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/PlanetB-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Planet_6.geometry} material={materials.Atlas}/>
    </group>
  )
}

useGLTF.preload('/PlanetB-transformed.glb')
