/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Planet.glb --transform 
Files: Planet.glb [72.25KB] > C:\Projekte\exogenesis\frontend\public\models\earth\Planet-transformed.glb [13.21KB] (82%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Planet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Planet_3.geometry} material={materials.Atlas} scale={25000} />
    </group>
  )
}

useGLTF.preload('/Planet-transformed.glb')
